name: Terraform GitHub Module
description: Run Terraform plan/apply with GitHub App authentication, GCS backend via Workload Identity, and tfcmt PR comments
author: ngdangdat

branding:
  icon: cloud
  color: purple

inputs:
  gh_app_id:
    description: GitHub App ID for authentication
    required: true
  gh_app_private_key:
    description: GitHub App Private Key (PEM format)
    required: true
  github_app_installation_id:
    description: GitHub App Installation ID
    required: true
  gcp_workload_identity_provider:
    description: GCP Workload Identity Provider (e.g., projects/123/locations/global/workloadIdentityPools/pool/providers/provider)
    required: true
  gcp_service_account:
    description: GCP Service Account email for Workload Identity
    required: true
  working_directory:
    description: Directory containing Terraform configuration
    required: false
    default: "."
  terraform_version:
    description: Terraform version to use
    required: false
    default: "latest"
  mode:
    description: "Terraform mode: 'plan' or 'apply'"
    required: false
    default: "plan"
  plan_args:
    description: Additional arguments for terraform plan
    required: false
    default: ""
  apply_args:
    description: Additional arguments for terraform apply
    required: false
    default: "-auto-approve"

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - name: Generate GitHub App Token
      id: app-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ inputs.gh_app_id }}
        private-key: ${{ inputs.gh_app_private_key }}

    - name: Setup aqua cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.local/share/aquaproj-aqua
          ~/.cache/aquaproj-aqua
        key: ${{ runner.os }}-aqua-tfcmt
        restore-keys: |
          ${{ runner.os }}-aqua-

    - name: Install aqua
      uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
      with:
        aqua_version: v2.36.1

    - name: Install tfcmt
      shell: bash
      run: |
        aqua init
        aqua g -i suzuki-shunsuke/tfcmt
        aqua i
        export PATH="$(aqua root-dir)/bin:$PATH"
        echo "$(aqua root-dir)/bin" >> $GITHUB_PATH
        tfcmt --version

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_APP_ID: ${{ inputs.gh_app_id }}
        GITHUB_APP_INSTALLATION_ID: ${{ inputs.github_app_installation_id }}
        GITHUB_APP_PEM_FILE: ${{ inputs.gh_app_private_key }}
      run: terraform init

    - name: Terraform Plan
      if: inputs.mode == 'plan'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_APP_ID: ${{ inputs.gh_app_id }}
        GITHUB_APP_INSTALLATION_ID: ${{ inputs.github_app_installation_id }}
        GITHUB_APP_PEM_FILE: ${{ inputs.gh_app_private_key }}
      run: tfcmt plan -- terraform plan ${{ inputs.plan_args }}

    - name: Terraform Apply
      if: inputs.mode == 'apply'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        GITHUB_APP_ID: ${{ inputs.gh_app_id }}
        GITHUB_APP_INSTALLATION_ID: ${{ inputs.github_app_installation_id }}
        GITHUB_APP_PEM_FILE: ${{ inputs.gh_app_private_key }}
      run: tfcmt apply -- terraform apply ${{ inputs.apply_args }}
