name: 'Install GitHub CLI'
description: 'Install gh (GitHub CLI) on Linux, macOS, and Windows runners'
author: 'Your Name'

branding:
  icon: 'terminal'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Setup aqua cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.local/share/aquaproj-aqua
          ~/.cache/aquaproj-aqua
        key: ${{ runner.os }}-aqua-${{ hashFiles('**/aqua.yaml') }}
        restore-keys: |
          ${{ runner.os }}-aqua-

    - name: Install aqua
      uses: aquaproj/aqua-installer@6ce1f8848ec8e61f14d57bd5d7597057a6dd187c # v3.0.1
      with:
        aqua_version: v2.36.1

    - name: Install gh with aqua
      shell: bash
      run: |
        aqua install -a
        echo "$(aqua root-dir)/bin" >> $GITHUB_PATH
        gh --version
