name: 'Install GitHub CLI'
description: 'Install gh (GitHub CLI) on Linux, macOS, and Windows runners'
author: 'ngdangdat'

branding:
  icon: 'terminal'
  color: 'blue'

runs:
  using: 'composite'
  steps:
    - name: Setup aqua cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.local/share/aquaproj-aqua
          ~/.cache/aquaproj-aqua
        key: ${{ runner.os }}-aqua-${{ hashFiles('aqua.yaml') }}
        restore-keys: |
          ${{ runner.os }}-aqua-

    - name: Install aqua
      uses: aquaproj/aqua-installer@f6be09d5313d3af86e3ad665911c67b149a4498c # v4.0.4
      with:
        aqua_version: v2.56.2

    - name: Install gh with aqua
      shell: bash
      run: |
        if [ ! -f aqua.yaml ]; then
          aqua init
          aqua g -i cli/cli
        fi
        aqua i
        export PATH="$(aqua root-dir)/bin:$PATH"
        echo "$(aqua root-dir)/bin" >> $GITHUB_PATH
        gh --version
