name: Terraform GCP Module
description: Run Terraform plan/apply with GCP Workload Identity authentication and tfcmt PR comments
author: ngdangdat

branding:
  icon: cloud
  color: blue

inputs:
  gcp_workload_identity_provider:
    description: GCP Workload Identity Provider (e.g., projects/123/locations/global/workloadIdentityPools/pool/providers/provider)
    required: true
  gcp_service_account:
    description: GCP Service Account email for Workload Identity
    required: true
  github_token:
    description: GitHub token for tfcmt PR comments
    required: true
  working_directory:
    description: Directory containing Terraform configuration
    required: false
    default: "."
  terraform_version:
    description: Terraform version to use
    required: false
    default: "latest"
  mode:
    description: "Terraform mode: 'plan' or 'apply'"
    required: false
    default: "plan"
  plan_args:
    description: Additional arguments for terraform plan
    required: false
    default: ""
  apply_args:
    description: Additional arguments for terraform apply
    required: false
    default: "-auto-approve"

runs:
  using: composite
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: ${{ inputs.gcp_workload_identity_provider }}
        service_account: ${{ inputs.gcp_service_account }}

    - name: Setup aqua cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        path: |
          ~/.local/share/aquaproj-aqua
          ~/.cache/aquaproj-aqua
        key: ${{ runner.os }}-aqua-${{ hashFiles('aqua.yaml') }}
        restore-keys: |
          ${{ runner.os }}-aqua-

    - name: Install aqua
      uses: aquaproj/aqua-installer@f6be09d5313d3af86e3ad665911c67b149a4498c # v4.0.4
      with:
        aqua_version: v2.56.2

    - name: Install tfcmt
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: |
        if [ ! -f aqua.yaml ]; then
          aqua init
          aqua g -i suzuki-shunsuke/tfcmt
        fi
        aqua i
        export PATH="$(aqua root-dir)/bin:$PATH"
        echo "$(aqua root-dir)/bin" >> $GITHUB_PATH
        tfcmt --version

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Terraform Init
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: terraform init

    - name: Terraform Plan
      if: inputs.mode == 'plan'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: tfcmt plan -- terraform plan ${{ inputs.plan_args }}

    - name: Terraform Apply
      if: inputs.mode == 'apply'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: tfcmt apply -- terraform apply ${{ inputs.apply_args }}
